In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.describe()

                 id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

KeyError: "['id', 'Unnamed: 32'] not found in axis"

In [ ]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
x_test,x_train,y_test,y_train = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=0)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_test

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
338       10.050         17.53  ...          0.2894                  0.07664
427       10.800         21.98  ...          0.2965                  0.07662
406       16.140         14.86  ...          0.2778                  0.07012
96        12.180         17.84  ...          0.2227                  0.07376
490       12.250         22.44  ...          0.3100                  0.08203
..           ...           ...  ...             ...                      ...
277       18.810         19.98  ...          0.2567                  0.05737
9         12.460         24.04  ...          0.4366                  0.20750
359        9.436         18.32  ...          0.2454                  0.08136
192        9.720         18.22  ...          0.1909                  0.06559
559       11.510         23.93  ...          0.2112                  0.08732

[455 rows x 30 columns]

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
xr_tensor = torch.from_numpy(x_train)
xt_tensor = torch.from_numpy(x_test)
yr_tensor = torch.from_numpy(y_train)
yt_tensor = torch.from_numpy(y_test)

In [ ]:
class SimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1 , dtype=torch.float64, requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def lossfunc(self,y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon,)
    loss = -(yr_tensor * torch.log(y_pred) + (1 - yr_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [ ]:
lr = 0.1
epochs = 25

In [ ]:
model = SimpleNN(xr_tensor)

for epoch in range(epochs):

  y_pred = model.forward(xr_tensor)

  loss = model.lossfunc(y_pred,yr_tensor)

  loss.backward()

  with torch.no_grad():

    model.weights -= lr*model.weights.grad
    model.bias -= lr*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.6349781829626266
Epoch: 2, Loss: 3.4643667173667447
Epoch: 3, Loss: 3.294350709741379
Epoch: 4, Loss: 3.1210546546801137
Epoch: 5, Loss: 2.9511336505001835
Epoch: 6, Loss: 2.7853747114261966
Epoch: 7, Loss: 2.624634525165639
Epoch: 8, Loss: 2.4697777408963044
Epoch: 9, Loss: 2.321625676539504
Epoch: 10, Loss: 2.1763047583854207
Epoch: 11, Loss: 2.016464420613011
Epoch: 12, Loss: 1.8562185620015206
Epoch: 13, Loss: 1.708931516864729
Epoch: 14, Loss: 1.5756990542023472
Epoch: 15, Loss: 1.4519968978213096
Epoch: 16, Loss: 1.335433330472225
Epoch: 17, Loss: 1.2356955815205046
Epoch: 18, Loss: 1.1525518792174478
Epoch: 19, Loss: 1.0849869637770655
Epoch: 20, Loss: 1.0311569041242017
Epoch: 21, Loss: 0.9887320459151794
Epoch: 22, Loss: 0.9553454271943386
Epoch: 23, Loss: 0.9288839551612191
Epoch: 24, Loss: 0.907595042978962
Epoch: 25, Loss: 0.8900963997160262

In [ ]:
with torch.no_grad():
  y_pred = model.forward(xt_tensor)
  y_pred = (y_pred>0.9).float()
  accuracy = (y_pred == yt_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6258906126022339